project-name: audio-deepfake-detection
active-job-id: ASVspoof-2019_small-eval-1

job-defaults:
  input-file-batch-size: 1000
  output-folder: output
  data-path-root: $HOMEDRIVE$HOMEPATH/workspace/Deepfake/data/ASVspoof-2019
  data-extension: .flac
  # Assign 'None' to training-split-random-state to get random split. Pass same int for reproducible split.
  training-split-random-state: 3
  labels-execute-to-categorical: true
  num-classes: 2        # Number of classes (bonafide and spoof)
  sample-rate: 16000
  duration: 5
  num-mels: 128
  max-time-steps: 109
  batch-size: 32
  num-epochs: 10
  optimizer: adam
  loss: categorical_crossentropy
  metrics:
    - accuracy

jobs:
  ASVspoof-2019_training:
    data-path-suffix: LA/ASVspoof2019_LA_train/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt
  ASVspoof-2019_small-eval-1:
    data-path-suffix: LA/ASVspoof2019_LA_eval_small/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval-small.trl.txt
    persisted-model: results/2025-03-23T13-49-37.076926/ASVspoof-2019_training_2025-03-23T13-49-37.076926.libjob
  ASVspoof-2019_eval-1:
    data-path-suffix: LA/ASVspoof2019_LA_eval/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
    persisted-model: results/2025-03-23T13-49-37.076926/ASVspoof-2019_training_2025-03-23T13-49-37.076926.libjob
  ASVspoof-2019_eval-1_large-batch:
    data-path-suffix: LA/ASVspoof2019_LA_eval/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
    persisted-model: results/2025-03-23T13-49-37.076926/ASVspoof-2019_training_2025-03-23T13-49-37.076926.libjob
    input-file-batch-size: 4000
  ASVspoof-2019_eval-1_huge-batch:
    data-path-suffix: LA/ASVspoof2019_LA_eval/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
    persisted-model: results/2025-03-23T13-49-37.076926/ASVspoof-2019_training_2025-03-23T13-49-37.076926.libjob
    input-file-batch-size: 71237