project-name: main-audio-deepfake-detection
active-job-id: ASVspoof-2019-1

jobs:
  ASVspoof-2019-1:
    data-path: $HOMEDRIVE$HOMEPATH/workspace/Deepfake/data/ASVspoof-2019
    training-data-path: LA/ASVspoof2019_LA_train/flac
    training-data-extension: .flac
    training-label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt

