project-name: audio-deepfake-detection
active-job-id: ASVspoof-2019_small-eval-1

job-defaults:
  input-file-batch-size: 1000
  data-path-root: $HOMEDRIVE$HOMEPATH/workspace/Deepfake/data/ASVspoof-2019
  data-extension: .flac
  labels-execute-to-categorical: true
  num-classes: 2        # Number of classes (bonafide and spoof)
  sample-rate: 16000
  duration: 5
  num-mels: 128
  max-time-steps: 109
  batch-size: 32
  num-epochs: 10
  optimizer: adam
  loss: categorical_crossentropy
  metrics:
    - accuracy

jobs:
  ASVspoof-2019_training:
    data-path-suffix: LA/ASVspoof2019_LA_train/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt
  ASVspoof-2019_small-eval-1:
    data-path-suffix: LA/ASVspoof2019_LA_eval_small/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval-small.trl.txt
    persisted-model: ASVspoof-2019-1_2025-03-19T22-03-42.178503.libjob
  ASVspoof-2019_eval-1:
    data-path-suffix: LA/ASVspoof2019_LA_eval/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
    persisted-model: ASVspoof-2019-1_2025-03-19T22-03-42.178503.libjob
  ASVspoof-2019_small-eval-2:
    data-path-suffix: LA/ASVspoof2019_LA_eval_small/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval-small.trl.txt
    persisted-model: ASVspoof-2019_2025-03-20T21-12-12.129665.libjob
