project-name: audio-deepfake-detection
active-job-id: ASVspoof-2019_small-eval-1

job-defaults:
  input-file-batch-size: 1000
  output-folder: output
  data-path-root: $HOMEDRIVE$HOMEPATH/workspace/Deepfake/data/ASVspoof-2019
  data-extension: .flac
  # Assign 'None' to training-split-random-state to get random split. Pass same int for reproducible split.
  training-split-random-state: 3
  labels-execute-to-categorical: true
  classes:
    - spoof
    - bonafide
  sample-rate: 16000
  duration: 5
  num-mels: 128
  max-time-steps: 109
  kernel-size: (2, 2)
  pool-size: (2, 2)
  batch-size: 32
  num-epochs: 10
  optimizer: adam
  loss: categorical_crossentropy
  metrics:
    - accuracy
  preprocessor: mel_spectrogram

jobs:
  # Training
  ASVspoof-2019_training:
    data-path-suffix: LA/ASVspoof2019_LA_train/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt
    training-split-random-state: 186
  ASVspoof-2019_training_epoch-100:
    data-path-suffix: LA/ASVspoof2019_LA_train/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt
    training-split-random-state: 186
    num-epochs: 100
  ASVspoof-2019_training-mfcc:
    data-path-suffix: LA/ASVspoof2019_LA_train/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.train.trn.txt
    training-split-random-state: 186
    preprocessor: mfcc
  GitLab-training-data:
    data-path-root: .
    data-path-suffix: testaudio-sksmta
    label-filename: testvalues/sksmta.train.trn.txt
  # Validation
  ASVspoof-2019_testing:
    data-path-suffix: LA/ASVspoof2019_LA_eval/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
    persisted-model: results/final_epoch__10/ASVspoof-2019_training_2025-04-13T13-20-29.862262.libjob
  ASVspoof-2019_testing-1:
    data-path-suffix: LA/ASVspoof2019_LA_eval/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
    persisted-model: results/2025-04-18T10-25-30.270494_epoch_10/ASVspoof-2019_training_2025-04-18T10-25-30.270494.libjob
  ASVspoof-2019_testing_epoch-100:
    data-path-suffix: LA/ASVspoof2019_LA_eval/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
    persisted-model: results/final_epoch_100/ASVspoof-2019_training_epoch-100_2025-04-13T18-36-22.832711.libjob
  ASVspoof-2019_testing-mfcc:
    data-path-suffix: LA/ASVspoof2019_LA_eval/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
    persisted-model: results/final_epoch__10_mfcc/ASVspoof-2019_training-mfcc_2025-04-13T20-58-59.037165.libjob
    preprocessor: mfcc
  GitLab-eval-data:
    data-path-root: .
    data-path-suffix: testaudio
    label-filename: testvalues/LA.cm.train.trn.txt
    persisted-model: results/2025-04-12T22-43-08.984941_0.0.3_gitlab/GitLab-training-data_2025-04-12T22-43-08.984941.libjob-for-test
  # Validation (bulk)
  ASVspoof-2019_training_split069_epoch10:
    data-path-suffix: LA/ASVspoof2019_LA_eval/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
    persisted-model: results/Tag-0.0.6/2025-04-18T14-23-21.325235_epoch_10_random/01_ASVspoof-2019_training_2025-04-18T14-23-21.325235_random_000069.libjob
  ASVspoof-2019_training_split147_epoch10:
    data-path-suffix: LA/ASVspoof2019_LA_eval/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
    persisted-model: results/Tag-0.0.6/2025-04-18T14-23-21.325235_epoch_10_random/02_ASVspoof-2019_training_2025-04-18T14-23-21.325235_random_000147.libjob
  ASVspoof-2019_training_split133_epoch10:
    data-path-suffix: LA/ASVspoof2019_LA_eval/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
    persisted-model: results/Tag-0.0.6/2025-04-18T14-23-21.325235_epoch_10_random/02_ASVspoof-2019_training_2025-04-18T14-23-21.325235_random_000133.libjob
  ASVspoof-2019_training_split105_epoch10:
    data-path-suffix: LA/ASVspoof2019_LA_eval/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
    persisted-model: results/Tag-0.0.6/2025-04-18T14-23-21.325235_epoch_10_random/02_ASVspoof-2019_training_2025-04-18T14-23-21.325235_random_000105.libjob
  ASVspoof-2019_training_split186_epoch10:
    data-path-suffix: LA/ASVspoof2019_LA_eval/flac
    label-filename: LA/ASVspoof2019_LA_cm_protocols/ASVspoof2019.LA.cm.eval.trl.txt
    persisted-model: results/Tag-0.0.6/2025-04-18T14-23-21.325235_epoch_10_random/02_ASVspoof-2019_training_2025-04-18T14-23-21.325235_random_000186.libjob
