project-name: audio-deepfake-detection
active-job-id: ASVspoof-2019-2

job-defaults:
  input-file-batch-size: 1000
  output-folder: output
  data-path-root: .
  data-extension: .flac
  # Assign 'None' to training-split-random-state to get random split. Pass same int for reproducible split.
  training-split-random-state: 3
  labels-execute-to-categorical: true
  num-classes: 2        # Number of classes (bonafide and spoof)
  sample-rate: 16000
  duration: 5
  num-mels: 128
  max-time-steps: 109
  batch-size: 32
  num-epochs: 10
  optimizer: adam
  loss: categorical_crossentropy
  metrics:
    - accuracy

jobs:
  ASVspoof-2019-1:
    data-path-suffix: testaudio
    label-filename: testvalues/LA.cm.train.trn.txt
  ASVspoof-2019-2:
    data-path-suffix: testaudio
    label-filename: testvalues/LA.cm.train.trn.txt
